program ::= statement?

statement ::= expression
            | 

expression ::= binaryExpression
             | ternaryExpression
             | primary
             | unaryExpression

binaryExpression ::= 

dataType ::= "String" | "int" | "float" | "boolean" | "char"

primary ::= dataType && VALUE
