program ::= statementList

statementList ::= statement+

block ::= "{" statementList "}"

statement ::= functionCall
            | assignment
            | conditionalStatement
            | loopStatement
            | functionDefinition
            | initialization
            | variableDeclaration

expression ::= binaryExpression
             | ternaryExpression
             | primary
             | unaryExpression

binaryExpression ::= primary binaryOperator primary ";"

binaryOperator ::= simpleMathOperator | comparator | booleanOperators

simpleMathOperator ::= "+" | "-" | "*" | "/" | "%"

dataType ::= "String" | "int" | "float" | "boolean" | "char"

comparator ::= ">" | "<" | ">=" | "<=" | "==" | "!="

unaryExpression ::= primary unaryExpression ";"

unaryOperator ::= "++" | "--" | "!"

primary ::= NUMBER
          | STRING
          | IDENTIFIER
          | booleanLiteral
          | functionCall

assignment ::= variable "=" primary

conditionalStatement ::= "if" "(" expression ")" block

loopStatement ::= "while" "(" expression ")" block

variableDeclaration ::= dataType variableName ";"

variableName ::= STRING

initialization ::= dataType variableName "=" primary ";"

functionCall ::= functionName "(" parameter* ")" ";"

functionName ::= STRING
