program ::= statement?

statement ::= expression
            | functionCall
            | assignment
            | conditionalStatement
            | loopStatement
            | functionDefinition
            | initialization
            | variableDeclaration

expression ::= binaryExpression
             | ternaryExpression
             | primary
             | unaryExpression

binaryExpression ::= 

dataType ::= "String" | "int" | "float" | "boolean" | "char"

primary ::= dataType && VALUE
