package MarioKart.LexicalAnalysis;

public enum Type {
    //---------Keywords----------
    REQUIRES, RETURN, SUMMON, USING, GARAGE, COMMENT, TIMETRIAL, LAP, BY,

    //-----------Loop------------
    FROM, TO,

    //--------Conditional---------
    FIRST, 
    SECOND, THIRD, FOURTH, FIFTH, SIXTH,
    SEVENTH, EIGHTH, NINTH, TENTH, ELEVENTH, TWELFTH, 
    LAST,
    TRUE, FALSE, EQUALS, 

    //----------Data Types---------
    INT, STRING, BOOLEAN, REAL, ARRAY, CHAR,

    //---Single-Character Tokens---
    OPEN_PARENTHESIS, CLOSED_PARENTHESIS,
    OPEN_BRACKET, CLOSED_BRACKET,
    OPEN_CURLY, CLOSED_CURLY,
    SEMICOLON, DOT, COMMA,

    //----------Operators----------
    PLUS, MINUS, TIMES, DIVIDED_BY, MOD, 
    PLUS_EQUALS, MINUS_EQUALS, TIMES_EQUALS, DIVIDED_EQUALS,
    PLUS_PLUS, MINUS_MINUS,
    NOT, EQUALS_EQUALS, NOT_EQUALS,
    GREATER_THAN, GREATER_THAN_OR_EQUAL_TO, LESS_THAN, LESS_THAN_OR_EQUAL_TO,
    AND, OR,

    //--------sillies--------
    EMPTY_PROGRAM, STATEMENT_LIST, ERROR, END_OF_FILE, IDENTIFIER, PARAMETER, PARAMETER_LIST,
    FOR_STATEMENT, LOOP_STATEMENT, INITIALIZATION, VARIABLE_DECLARATION, BINARY_EXPRESSION,
    EXPRESSION, WHILE_STATEMENT, CONDITIONAL_BLOCK, IF_STATEMENT, ELSE_IF_STATEMENT, ELSE_STATEMENT,
    FUNCTION_CALL, FUNCTION_DEFINITION, NULL, FUNCTION, ASSIGNMENT, ARGUMENT_LIST,
}
